Features /cap 03
dulce-mejia29/curso-HTML5 pull request #4
Opened 2024-11-12 16:39 UTC by dulce-mejia29

agrego resumen del capitulo 3

2024-11-12 16:40 UTC, dulce-mejia29 commented
@semanticmx 
@Jorge-Sarabia

2024-11-12 18:28 UTC, Jorge-Sarabia requested changes
Te dejé comentarios sobre algunos cambios.

2024-11-12 18:28 UTC, Jorge-Sarabia commented on cap-03/README.md
> +**ELEMENTO <CABEZA>**
Cuidado con las traducciones, en HTML la etiqueta debe ser `<head>`.

2024-11-12 18:28 UTC, Jorge-Sarabia commented on cap-03/README.md
> +**RESUMEN CAPITULO 3**
Como este es el título del capítulo, sería mejor seguir las prácticas recomendadas de Markdown para títulos. En lugar de usar **negritas**, podríamos formatearlo como un encabezado con # Título para mantener consistencia y semántica.

2024-11-12 18:28 UTC, Jorge-Sarabia commented on cap-03/README.md
> +**PIE**
En este caso, sería más claro especificarlo como PIE DE PÁGINA o utilizar la etiqueta <footer> para mayor semántica y consistencia con las prácticas recomendadas.

2024-11-12 18:28 UTC, Jorge-Sarabia commented on cap-03/scr
Recuerda agregar la extensión del archivo. En este caso sería `scr.html`o `index.html`, para mantener la consistencia.

2024-11-12 18:28 UTC, Jorge-Sarabia commented on cap-03/scr
> +<head>
Recuerda mantener la indentación adecuada de las etiquetas para mejorar la legibilidad. En este caso, podría quedar de la siguiente manera:
```html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    ...
```

2024-11-19 21:35 UTC, dulce-mejia29 reviewed
listo

2024-11-20 17:18 UTC, semanticmx approved these changes
gracias

2025-01-21 17:41 UTC, merged