Features/cap 04
dulce-mejia29/curso-HTML5 pull request #5
Opened 2024-11-12 21:30 UTC by dulce-mejia29

resumen del capitulo 4 de HTML

2024-11-12 21:31 UTC, dulce-mejia29 commented
@semanticmx 
@Jorge-Sarabia

2024-11-12 23:34 UTC, semanticmx approved these changes
hay que mejorar el formato del código

2024-11-12 23:34 UTC, semanticmx commented on cap-04/README.md
> +`<canvas>id`
aquí sobró un `id`

2024-11-12 23:34 UTC, semanticmx commented on cap-04/README.md
> +for (var x = 0.5; x < 500; x += 10) {
el código hay que formatearlo con la sintaxis de código.

https://www.markdownguide.org/extended-syntax/#syntax-highlighting

2024-11-13 18:17 UTC, Jorge-Sarabia requested changes

2024-11-13 18:17 UTC, Jorge-Sarabia commented on cap-04/scr
Recuerda agregar la extensión del archivo. En este caso sería `src.html`

2024-11-13 18:17 UTC, Jorge-Sarabia commented on cap-04/scr
> +<head>
Agrega la indentación entre cada etiqueta HTML.

2024-11-20 17:07 UTC, semanticmx approved these changes
hay detalles de formato de texto y código que podemos corregir en los siguientes capituloa

2025-01-21 17:38 UTC, dulce-mejia29 reviewed
listo

2025-01-21 17:40 UTC, dulce-mejia29 reviewed
listo

2025-01-21 17:41 UTC, merged