Features/cap 05
dulce-mejia29/curso-HTML5 pull request #6
Opened 2024-11-18 06:02 UTC by dulce-mejia29

agrego resumen del capitulo  5

2024-11-18 06:02 UTC, dulce-mejia29 commented
@semanticmx 
@Jorge-Sarabia

2024-11-18 19:26 UTC, semanticmx requested changes
hay que aplicar este formato al código

https://github.com/semanticmx/html5-coding-standards?tab=readme-ov-file#proper-use-of-standards-in-html5

2024-11-18 19:26 UTC, semanticmx commented on cap-05/README.md
> +## Cdecs de vídeo
Debe decir `Codecs` o `Códecs`

2024-11-18 19:26 UTC, semanticmx commented on cap-05/README.md
> +Los códecs con pérdida logran una excelente compresión minimizando el impacto visual, pero cada recodificación degrada la calidad del video.
como aquí

2024-11-18 19:26 UTC, semanticmx commented on cap-05/index.html
> +            <param name="movie" value="flash-player.swf">
hay que aplicar el formato de atributos por favor.

2025-01-21 17:43 UTC, dulce-mejia29 reviewed
listo

2025-01-22 03:00 UTC, semanticmx requested changes

2025-01-22 03:00 UTC, semanticmx commented on cap-05/README.md
> +## Cdecs de vídeo
@dulce-mejia29 
Le falta una "o"

2025-01-22 19:52 UTC, Jorge-Sarabia requested changes
Solo queda pendiente aplicar el formato de atributos a las etiquetas, por favor.

2025-01-22 19:52 UTC, Jorge-Sarabia commented on cap-05/index.html
> +        <object type="application/x-shockwave-flash" data="flash-player.swf" width="640" height="360">
Siguiendo los estándares establecidos aquí [html5-coding-standards](https://github.com/semanticmx/html5-coding-standards?tab=readme-ov-file#proper-use-of-standards-in-html5) cuando una etiqueta HTML tiene múltiples atributos, cada atributo debe ir en su propia línea para mejorar la legibilidad y mantenibilidad del código.
Con base en este estándar, el formato de la etiqueta `<object>` quedaría de la siguiente manera:
  
```html
<object
    type="application/x-shockwave-flash"
    data="flash-player.swf"
    width="640"
    height="360"
>
```

Este formato debe aplicarse en las etiquetas restantes, por favor.

2025-01-26 04:21 UTC, dulce-mejia29 reviewed
listo

2025-01-26 04:24 UTC, dulce-mejia29 reviewed
listo

2025-01-26 04:26 UTC, merged